---
title: "eipes_try"
format: html
editor: visual
---

## Preliminary analyses for EIPES

A very quick summary of some basics

```{r warning = F, message = F}
library(tidyverse)
library(readxl)
```


```{r warning = F, message = F}
eipes_try <- read_excel("~/Downloads/ΕΡΕΥΝΑ ΓΙΑ ΤΗΝ ΙΑΤΡΙΚΗ ΠΑΙΔΕΙΑ ΚΑΙ ΕΡΓΑΣΙΑ (ΕΙΠΕς) (Απαντήσεις) (14).xlsx")

eipes_try <- eipes_try[!is.na(eipes_try$`Χρονική σήμανση`),]

```

```{r}

# data collected so far.
eipes_try <- eipes_try[eipes_try$`Σε τι κατηγορία ανήκετε ;`== "Ειδικευόμενος/η",]

dim(eipes_try)


```

Gender composition

```{r}
# Numbers Gender
counts_gender <- table(eipes_try$`Φύλο?`)
# Percentage
gender_tab <- prop.table(table(eipes_try$`Φύλο?`))


bp_gender <- barplot(gender_tab,main = "Φύλο", col = "skyblue",ylab = "ποσοστό", ylim = c(0, max(gender_tab) + 0.05))
text(bp_gender, gender_tab, labels = paste0(counts_gender), pos = 3, cex = 0.8, col = "black")


```

Age composition

```{r}

# Mean Age
mean_age <- mean(eipes_try$Ηλικία)
sd_age <- sd(eipes_try$Ηλικία)
text_label <- paste("μέση ηλικία =", round(mean_age, 2), "(", round(sd_age, 2), ")")


# Age Histogram
hist_gender <-  hist(eipes_try$Ηλικία, main = "Ηλικία" , col = "skyblue", xlab = "", 
                     ylab = "συχνότητα")
text(x = mean(range(hist_gender$breaks)), 
     y = max(hist_gender$counts-10), 
     labels = text_label, 
     pos = 3, 
     cex = 1, 
     col = "black")
```

How many are Trainees vs students

```{r}
# Students vs Trainees
table(eipes_try$`Σε τι κατηγορία ανήκετε ;`)
prop.table(table(eipes_try$`Σε τι κατηγορία ανήκετε ;`))


```

Type of Specialty

```{r}
library(kableExtra)
# Type of Speciality
by_specialty <- data.frame(table(eipes_try$`Ειδικότητα που έχετε επιλέξει?`))
colnames(by_specialty) <- c("specialty", "n")
by_specialty$percentage <- round(by_specialty$n/sum(by_specialty$n),2)
openxlsx::  write.xlsx(by_specialty, "by_specialty.xlsx")

knitr::kable(by_specialty)


```

Location of speciality

```{r}
# Where being specialised
counts_location <- table(eipes_try$`Κάνετε ειδικότητα στην?`)
location <- prop.table(table(eipes_try$`Κάνετε ειδικότητα στην?`))

bp <- barplot(location, main = "Πού Κάνεις Ειδικότητα" , col = "skyblue", ylab = "ποσοστό", ylim = c(0, max(location) + 0.05))
text(bp, location, labels = paste0(counts_location), pos = 3, cex = 0.8, col = "black")

```

Data collected by date

```{r}

# Sample POSIXct object
timestamp <- as.POSIXct(eipes_try$`Χρονική σήμανση`)

# Extract the date
eipes_try$date <- format(timestamp, "%Y-%m-%d")

# Determine AM or PM
eipes_try$am_pm <- ifelse(format(timestamp, "%p") == "AM", "AM", "PM")


# Dates and collected data (sorry they are not sorted)
count_per_day_and_time <- tapply(eipes_try$am_pm, list(as.Date(eipes_try$date), eipes_try$am_pm), length)

# names(count_per_day)
# counts <- as.numeric(count_per_day)

df_count_per_day_and_time <- data.frame(count_per_day_and_time)
df_count_per_day_and_time$date <-rownames(df_count_per_day_and_time)


df_count_per_day_and_time$AM[is.na(df_count_per_day_and_time$AM)] <- 0 # need to do this for base plot

counts_matrix <- as.matrix(df_count_per_day_and_time[, c("AM", "PM")]) # base prefers a matrix
rownames(counts_matrix) <- as.character(df_count_per_day_and_time$date)

barplot(t(counts_matrix), 
        beside = FALSE, 
        col = c("skyblue", "steelblue"), 
      main = paste("Ημερήσιος Αριθμός Συμμετεχόντων\n Σύνολο n = ", nrow((eipes_try))),
        xlab = "", 
        ylab = "Αριθμός Συμμετεχόντων", 
        legend.text = c("πρωί", "απόγευμα"),
        args.legend = list(x = "top", bty = "n"),
        las = 2, # Rotate x-axis labels
        cex.names = 0.8)



# df_count_per_day_and_time_long <- data.frame( 
#   
#   date = c(df_count_per_day_and_time$date ,
#        df_count_per_day_and_time$date), 
#   counts= c(df_count_per_day_and_time$AM,
#                    df_count_per_day_and_time$PM), 
#   
#   time_day = c(rep("AM", length(df_count_per_day_and_time$AM)),
#                rep("PM", length(df_count_per_day_and_time$AM))
#   )
#        
# )

# df_count_per_day_and_time_long %>% 
#   ggplot(aes(date, counts, fill = time_day)) +
#   geom_col()+
#   ggtitle("EIPES: numbers completed per day and time")+
#   theme(axis.text.x = element_text(face = "bold", color = "black",
# size = 10, angle = 45))
  
```



```{r}
prop.table(table(eipes_try$`Συμφωνείτε με το να υπάρχουν εξετάσεις για την έναρξη της ειδικότητας?...13`))

prop.table(table(eipes_try$`Πόση εμπιστοσύνη έχετε ότι το Υπουργείο Υγείας μπορεί να διασφαλίσει το αδιάβλητο εξετάσεων?...16`))


contingency_table <- table(
  eipes_try$`Συμφωνείτε με το να υπάρχουν εξετάσεις για την έναρξη της ειδικότητας?...13`, 
  eipes_try$`Πόση εμπιστοσύνη έχετε ότι το Υπουργείο Υγείας μπορεί να διασφαλίσει το αδιάβλητο εξετάσεων?...16`
)

contingency_table[categories_order]

contingency_table_with_margins <- addmargins(contingency_table)
categories_order <- c('Καθόλου', 'Λίγο', 'Αρκετά', 'Πολύ', 'Πάρα πολύ')
chisq.test(contingency_table)

contingency_matrix <- as.matrix(contingency_table)

# Create a color palette
colors <- colorRampPalette(c("white", "steelblue"))(100)

# Plot the heatmap
heatmap(
  contingency_matrix, 
  col = colors, 
  scale = "none", 
  margins = c(10, 10),
  xlab = "εξετάσεις για την έναρξη της ειδικότητας?",
  ylab = "εμπιστοσύνη sτο Υπουργείο Υγείας για εξετάσεις?",
  main = "Εξετάσεις και Εμπιστοσύνη",
  cexRow = 0.8,
  cexCol = 0.8
)





percentage_table_with_margins


prop.table(table(eipes_try$`Γενικώς πόσο ευχαριστημένος/η είστε από την ειδικότητα που έχετε επιλέξει?`))

prop.table(table(eipes_try$`Ειδικεύεστε σε?` ))


prop_table <- prop.table(table(eipes_try$`Πόσο σκέφτεστε να μετακομίσετε στο εξωτερικό μετά την ειδικότητα?`))


categories_order <- c('Καθόλου', 'Λίγο', 'Αρκετά', 'Πολύ', 'Πάρα πολύ')
prop_table <- prop_table[categories_order]

barplot(prop_table,  main =  "Πόσο σκέφτεστε να μετακομίσετε στο εξωτερικό μετά την ειδικότητα?",col = "skyblue" )



#col = "skyblue",


```

