---
title: "KESY"
format: docx
editor: visual
---

# Γνωμοδότηση προς το Κεντρικο Συμβούλιο Υγείας

## Σύνοψη
επίκειται


## Γνωμοδότηση

1.  Μου εζητήθη από τον Πρόεδρο της Επιτροπής Ψυχικής Υγείας του Κεντρικού Συμβουλίου Υγείας (ΚΕΣΥ) Καθ. Νικ. Σμυρνή, να γνωμοδοτήσω επί του [υπ. αρ. Πρωτοκολλου 8479/02.04.2024 έγγραφο της Αναπλ. Διευθ. Ιατρική Υπηρεσίας του Νοσοκομείου Παίδων Αγ. Σοφια κας Ελ. Μπούζα με Θέμα Εισαγωγή Και Νοσηλεία Παιδοψυχιατρικών Περιστατικών]{.underline}. Το έγγραφο αυτό επισυνάπτεται ως παράρτημα Π1 στην παρουσα.

2.  Το ως άνω έγγραφο επί του οποίου γνωμοδοτώ όπως μου επεδόθη από το ΚΕΣΥ φέρει ως εισαγωγή διαβιβαστικό έγγραφο του Διοικητού κ. Εμμ. Παπασάββα με ημερομηνία 08.04.2024 (άνευ Αρ. Πρωτ) με την σφραγίδα του Νοσοκομείο. Στο διαβιβαστικό έγγραφο, το οποίο κοινοποιείτο σε Διευθύντριες και Διευθυντές πολλαπλών Κλινικών του Νοσοκομείου, εζητήθη η «πιστή εφαρμογή του  8479/02.04.2024 εγγράφου». Το έγγραφο αυτό επίσης επισυνάπτεται ως παράρτημα Π2 στην παρούσα.

3.  Ως γνωστόν, το Νοσοκομείο Παίδων Αγ. Σοφία είναι ένα το μεγαλύτερο νοσοκομείο για παιδιά και εφήβους στην Ελλάδα και ένα από τα μεγαλύτερα στην Ευρώπη και εμπεριέχει την φημισμένη Α´ Πανεπιστημιακή Παιδιατρική Κλινική η οποία βρίσκεται από ιδρύσεώς της στην πρωτοπορία της προόδου στον τομέα της στην χώρα μας με διεθνώς καταξιωμένους επιστήμονες. Επίσης, στο Παίδων Αγ. Σοφία βρίσκεται και η Πανεπιστημιακή Παιδοψυχιατρική Κλινική Ψυχιατρικής, η πρώτη και μεγαλύτερη στην Ελλάδα που παρέχει υπηρεσίες υψηλής ποιότητος και εύρους τόσο στην μορφή εξωτερικών ιατρείων όσο και ενδονοσοκομειακής νοσηλείας.

4.  Γνωμοδοτώ με τις ιδιότητές μου ως Καθηγητή Ψυχιατρικής Παιδιών και Εφήβων στο ΕΚΠΑ, Καθηγητής της Έδρας της Παιδοψυχιατρικής στο University College London (UCL), Αντιπρύτανη επί θεμάτων Ψυχικής στο UCL, και ως ειδικού επί ζητημάτων κατάθλιψης, επιθετικότητας και αυτοκαταστροφικών συμπεριφορών με διεθνώς ανεγνωρισμένο πρωτογενές έργο στους τομείς αυτούς (π.χ. World Highly Cited Author, Clarivate 2022) καθώς και κλινικό έργο ως πρώην Διευθυντής Εθνικού Κέντρου Αναφοράς για την Κατάθλιψη στο Νοσοκομείο Maudsley και στο King’s College London καθώς και ως πρώην Διευθυντής του Πρόγραμματος Κατάθλιψης στο National Institutes of Health (NIH) με υπερδεκαετές διοικητικό-κλινικό έργο σε θαλάμους νοσηλείας, εξωτερικά ιατρεία καθώς και Εθνικές επιτροπές για την Ψυχική Υγεία, μεταξύ άλλων και ως Πρόεδρος (εώς το 2023) της Επιτροπής Ψυχικής Υγείας του ΚΕΣΥ στη χώρα μας.

5.  Το έγγραφο υπ. αρ. Πρωτοκολλου 8479/02.04.2024 (εφεξής αναφερόμενο ως Έγγραφο) αναφέρει μεταξύ άλλων ότι «[ασθενείς με γνωστό ψυχιατρικό νόσημα (αυτοκτονική ή επιθετική συμπεριφορά)…δεν δύνανται να νοσηλεύονται σε παιδιατρικές κλινικές]{.underline}» και ότι «[τα παιδιά θα νοσηλεύονται σε παιδοψυχιατρικές κλινικές, όπου οι παιδίατροι θα παρέχουν τις παιδιατρικές συμβουλές]{.underline}». Το Έγγραφο του οποίου ο κ. Διοικητής του Νοσοκομείου ζητεί την «πιστή εφαρμογή» υπέχει λοιπόν χαρακτήρα οδηγίας προς τους εργαζομένους του νοσοκομείου την οποίαν αυτοί οφείλουν να εφαρμόσουν. Παρακάτω καταδεικνύω προβλήματα του Εγγράφου και εισηγούμαι τις δέουσες αλλαγές.

6.  [Η εφαρμογή του Εγγράφου επιφέρει σημαντικούς κινδύνους για την σωματική υγεία των ασθενών.]{.underline}  Τούτο επειδή το Έγγραφο προβλέπει ότι ασθενείς με «αυτοκτονική ή επιθετική συμπεριφορά» συλλήβδην θα πρέπει να νοσηλεύονται σε παιδοψυχιατρικές κλινικές στις οποίες οι παιδίατροι «θα παρέχουν παιδιατρικές συμβουλές». Ως γνωστόν, παιδιά με αυτοκτονικές συμπεριφορές έχουν συχνότατα ανάγκη εντατικής παιδιατρικής παρακολούθησης και θεραπείας διότι συχνά κινδυνεύει η ζωή τους συνεπεία του αυτοτραυματισμού τους. Παραθέτω δύο παραδείγματα προς κατανόηση του προβλήματος.

7.  Ένας από τους συχνότερους λόγους προσελεύσεως ή διακομιδής στα Επείγοντα περιστατικά Παιδιατρικού Νοσοκομείου είναι η δηλητηρίαση λόγω υπερβολικής δόσης με παρακεταμόλη (CITE). Ως γνωστόν, η δηλητηρίαση με παρακεταμόλη απαιτεί εξειδικευμένες εξετάσεις κλινικές  και εργαστηριακές (π.χ. επίπεδα αίματος μεταβολιτών), αλλά κυρίως θεραπεία μ.α. μέσω υποστήριξης των ζωτικών λειτουργειών του ασθενούς, χορηγήσεως αντιδότου (CITE) και στενής παρακολουθήσεως της λειτουργείας ου ήπατος και άλλων ζωτικών οργάνων. Σύμφωνα με το Έγγραφο, αυτού του είδους η νοσηλεία και θεραπεία θα γίνεται πλέον σε Παιδοψυχιατρική Κλινική και όχι στην Παιδιατρική. Η πρακτική αυτή στην οποία προτρέπει το Έγγραφο αποτελεί παγκόσμια πρωτοτυπία και είναι για προφανείς λόγους δυνητικά καταστροφική για τους ασθενείς η οποίοι χρήζουν στενής ιατρικής παρακολούθησης από εξειδικευμένοι παιδιατρική και νοσηλευτική ομάδα με όλα τα αναγκαία μέσα.

8.  Το έγγραφο επικαλείται την «επιθετικότητα» ως διάγνωση για την οποία επίσης προβλέπει ότι θα πρέπει παιδιά με επιθετικότητα επίσης συλλήβδην να νοσηλεύονται στην Παιδοψυχιατρική Κλινική. Ως γνωστόν, όμως, η επιθετική συμπεριφορά είναι συχνή σε παιδιατρικούς ασθενείς σε όλο το εύρος των παιδιατρικών νοσημάτων. Για παράδειγμα παιδιά με διαβητική κετοξέωση ή με υπογλυκαιμία στα πλαίσια θεραπείας του Σακχαρωδους Διαβήτου συχνότατα  μπορεί να παρουσιάσουν επιθετική συμπεριφορά αιτία της υποστρωματικής νόσου. Σύμφωνα με το έγγραφο, η επιθετικότητα αποτελεί «γνωστό παιδοψυχιατρικό νόσημα» και έτσι τα παιδιά αυτά θα έπρεπε να νοσηλεύονται στην Παιδοψυχιατρική Κλινική. Είναι προφανές ότι αυτό θα ήταν επίσης σκανδαλωδώς κακή πρακτική.

9.  Η εφαρμογή του Εγγράφου [επιφέρει σημαντικούς κινδύνους για την ψυχική υγεία των ασθενών]{.underline}.  Οι κίνδυνοι αυτοί προκύπτουν από το γεγονός ότι η επιβολή ψυχιατρικής νοσηλείας σε ασθενείς για τους οποίους δεν συντρέχει λόγος τέτοιας νοσηλείας επιβαρύνονται σημαντικά. Συχνά οι αυτοτραυματισμοί δεν προκύπτουν λόγω συγκεκριμένων διαταραχών ή διαταραχών που χρήζουν ενδονοσοκομειακής νοσηλείας. Αντιθέτως, συχνά οι αυτοτραυματισμοί προκύπτουν σε συνθήκες διαπροσωπικής έντασης (π.χ. χωρισμοί ή διαφωνίες με γονείς) επί εδάφους χρονίων προβλημάτων (π.χ. είναι συχνοί σε παιδιά με ιστορικό ψυχικού τραύματος). Για αυτά τα παιδιά, η ενδονοσοκομειακή ψυχιατρική νοσηλεία αποτελεί αναίτια ιατρική παρέμβαση που μπορεί να επιβαρύνει την κατάσταση του παιδιού, μεταξύ άλλων και λόγω του κοινωνικού στίγματος.

10. Η διεθνώς καλή πρακτική συνοψίζεται στα εξής χαρακτηριστικά:

    Πρώτον, την διακρίβωση και τεκμηρίωση του κινδύνου για τον ασθενή, το λεγόμενο Risk Assessment. Η νοσηλεία είναι απαραίτητη όχι βάσει συμπεριφορών γενικώς και αορίστως, αλλά αποφασίζεται μόνον αν η σωματική ακεραιότητα του ασθενούς ή αυτή άλλων τίθεται εν κινδύνω.

    Δεύτερον, την κατά το δυνατόν, λιγότερο παρεμβατική και ελάχιστα στιγματιστική υποστήριξη του ασθενούς. Τρίτον, στην στενή συνεργασία μεταξύ Παιδιάτρων και Παιδοψυχιάτρων για τον σχεδιασμό υπηρεσιών και την κοινή επιχειρησιακή προσπάθεια στην εξυπηρέτηση των ασθνενών.

11. Ο Παγκόσμιος Οργανισμός Υγείας αναφέρει: «Hospitalization in non-specialized services of general hospitals with the goal of preventing acts of self-harm is not routinely recommended for persons with self-harm. However, admission to general hospital for management of medical consequences of an act of self-harm may be necessary» υποστηρίζοντας την βραχεία νοσηλεία για την αποτροπή των ιατρικών συνεπειών του αυτοτραυματισμού.

12. Στο ίδιο πνεύμα κινούνται οι οδηγίες των διεθνώς ανεγνωρισμένων οδηγιών του Ινστιτούτου [National Institute of Clinical Excellence](https://www.nice.org.uk/guidance/ng225/chapter/Recommendations#admission-to-and-discharge-from-hospital) του Ηνωμένου Βασιλείου όπου γίνεται λόγος μόνον για [νοσηλεία σε γενικό νοσοκομείο]{.underline} (παιδιατρικό για ανήλικους) όταν συντρέχει ιατρικός η άλλος κίνδυνος και δεν συντρέχει λόγος ψυχιατρικής νοσηλείας (π.χ. ψύχωση ή επεισόδιο μανίας).  Είναι ευνόητο ότι τα ιατρικά προβλήματα που προκύπτουν από τον αυτοτραυματισμό αντιμετωπίζονται από την εξειδικευμένη παιδιατρική ομάδα στον οικείο χώρο. Μπορώ εδώ να αναφέρω και από την ιδία μου εμπειρία, ότι στην Βρετανία θα ήταν ανήκουστο για ένα παιδί με αυτοτραυματισμό που χρήζει νοσηλείας να μην νοσηλευθεί σε Παιδιατρική Κλινική, ειδικά σε παιδιά 16 και κάτω.

13. Αντίστοιχες είναι οι οδηγίες της Γερμανικής Εταιρείας Παιδοψυχιατρικής  (Deutsche Gesellschaft für Kinder- und Jugendpsychiatrie, Leitlinie AWFF Reg Nr 028/031, Klasse S2K) σε Συνεργασία με τον Παγγερμανικό Ιατρικό Σύλλογο (Bundesärztekammer), όπου και πάλι πρώτα ολοκληρώνεται η ιατρική περίθαλψη και κατόπιν γίνεται οποιαδήποτε αξιολόγηση για τυχόν ψυχιατρική νοσηλεία.

14. Η εφαρμογή του Εγγράφου ενέχει πιθανώς [σημαντικά νομικά ζητήματα]{.underline} για τα οποία θα πρέπει να ζητηθεί και νομική συνδρομή. Συγκεκριμένα,

15. Ο Κώδικας Ιατρικής Δεοντολογίας της Ελλάδας (Ν. 3418/2005) περιέχει τις διατάξεις που καθορίζουν τα καθήκοντα και τις ευθύνες των ιατρών. Στο άρθρο 3, παράγραφος 1, αναφέρεται ότι οι ιατροί οφείλουν να ασκούν το επάγγελμά τους σύμφωνα με τις αρχές της ιατρικής επιστήμης και της επαγγελματικής δεοντολογίας. Εν προκειμένω, το Έγγραφο αντιβαίνει τις αρχές της Ιατρικής Επιστήμης (βλ. σημεία 6 και 7 ανωτέρω) και θέτει ζητήματα ορθής άσκησης του ιατρικού επαγγέλματος από όσους εφαρμόζουν την οδηγία, είτε παιδιάτρους είτε ψυχιάτρους.

16. Ο Κώδικας Ιατρικής Δεοντολογίας, στο άρθρο 3, παράγραφος 2, αναγνωρίζει την επαγγελματική αυτονομία των ιατρών και τους υποχρεώνει να ασκούν το επάγγελμά τους με γνώμονα το καλύτερο συμφέρον του ασθενούς, βασιζόμενοι στην επιστημονική γνώση και τις επαγγελματικές τους δεξιότητες. Το Έγγραφο αντιβαίνει τις βέλτιστες πρακτικές με γνώμονα το καλύτερο συμφέρον του ασθενούς και ως εκ τούτου εγείρει ζητήματα που άπτονται του Κώδικος για όσους τον εφαρμόζουν.

17. Ο Κώδικας Ιατρικής Δεοντολογίας, στο άρθρο 4, προβλέπει ότι ο ιατρός πρέπει να προάγει την ίση πρόσβαση στις υπηρεσίες, όμως στο Έγγραφο γίνεται, ως μη ώφειλε, διάκριση μεταξύ ψυχιατρικών και άλλων ασθενών, η οποία παραβιάζει αυτήν την αρχή.

18. O Νόμος 3304/2005 - Εφαρμογή της Αρχής της Ίσης Μεταχείρισης Ανεξαρτήτως Φυλής ή Εθνοτικής Καταγωγής, Θρησκευτικών ή Άλλων Πεποιθήσεων, Αναπηρίας, Ηλικίας ή Σεξουαλικού Προσανατολισμού, εναρμονίζει την ελληνική νομοθεσία με την Οδηγία 2000/43/ΕΚ και την Οδηγία 2000/78/ΕΚ της Ευρωπαϊκής Ένωσης. Το Έγγραφο μεταχειριζόμενο ψυχιατρικούς ασθενείς ή ασθενείς με υποψία ψυχιατρικών συμπτωμάτων με διαφορετικο´τρόπο, φαίνεται να αντιβαίνει αυτόν τον Νόμο.

19. Ο Νόμος 2251/1994 (Προστασία των Καταναλωτών), άρθρο 8, προβλέπει ότι οι ιατροί μπορεί να θεωρηθούν υπεύθυνοι για ιατρική αμέλεια αν παρέχουν θεραπείες που δεν ευθυγραμμίζονται με τα αποδεκτά ιατρικά πρότυπα και προκαλέσουν βλάβη στον ασθενή. Το Έγγραφο δεν ευθυγραμμίζεται με τα ιατρικά πρότυπα και συνεπώς δύναται να εγείρει ζητήματα ιατρικής ευθύνης σε όσους τον εφαρμόζουν.

20. Με βάση τα παραπάων, προτείνω τα εξής:

    -   Όπως καταδεικνύω παραπάνω το έγγραφο έχει προβλήματα που καθιστούν απαραίτητη την επίσημη ανάκλησή του από τον Διοικητή με συνοδό επεξηγητικό σημείωμα.

    -   Η συνεργασία μεταξύ των Παιδιάτρων και Παιδοψυχιάτρων είναι απαραίτητη προϋπόθεση για την βέλτιστη παροχή υπηρεσιών στους ασθενείς. Το Νοσοκομείο Παίδων Αγία Σοφία έχει στις τάξεις τους εξέχουσες ιατρούς και στους δύο κλάδους, Παιδιατρικής και Παιδοψυχιατρικής, με μακρά παράδοση αρμονικής επιστημονικής συνεργασίας προς όφελος των ασθενών. Αντί καθέτως επιβαλλομένων οδηγιών, η Διοίκηση του Νοσοκομείου θα είναι καλό να ζητήσει από τις κ. Διευθύντριες Καθηγήτριες των Κλινικών να δημιουργήσουν τα κατάλληλα πρωτόκολλα και δομές για την βέλτιστη αντιμετώπιση του  προβλήματος. Πρόκειται για επιστήμονες διεθνούς βεληνεκούς με άριστη γνώση των προβλημάτων. Για παράδειγμα, η Α´Παιδιατρική Κλινική έχει ήδη σειρά πρωτοκόλλων για την αντιμετώπιση διαφόρων κλινικών οντοτήτων και περιστατικών. Η διε-επιστημονική ανάπτυξη αντιστοίχων για τα περιστατικά αυτοτραυματισμού και επιθετικότητας θα είναι ευχής έργον. Η συμμετοχής της κ. Αναπλ. Διευθυντού της Ιατρικής Υπηρεσίας και η αποτύπωση των προβλημάτων που οδήγησαν στο Έγγραφο θα είναι επίσης χρήσιμες.

    -   Έμφαση θα πρέπει να δοθεί στην Εκπαίδευση του προσωπικού του νοσκομείου. Το Έγγραφο βασίζεται σε έναν κάθετο δυϊστικό  διαχωρισμό μεταξύ παιδιατρικής και παιδοψυχιατρικής φροντίδος. Η σύγχρονη βέλτιστη πρακτική όμως εντοπίζεται στο ότι (και) η ψυχική υγεία είναι υπόθεση όλων και σε μεγάλο βαθμό και των παιδιάτρων, πράγμα που αποτυπώνεται σαφώς στις πρόσφατες οδηγίες του [Βασιλικού Κολλεγίου Παιδιάτρων](https://www.rcpch.ac.uk/resources/role-of-paediatricians-child-mental-health-position).  Τόσο στο ιατρικό όσο και στο νοσηλευτικό προσωπικό θα πρέπει να προσφέρεται εκπαίδευση σχ. με προβλήματα ψυχικής υγείας και αυτοτραυματισμού και αυτοκτονικότητας. Κατά το δυνατον ελάχιστα παρεμβατικές αντιμετωπίσεις που βασίζονται στην επιστημονική τεκμηρίωση θα πρέπει να βρίσκονται στο επίκεντρο τέτοιων εκπαιδεύσεων.

    -   Η Πολιτεία δια του Υπουργείου Υγείας και των αρμοδίων οργάνων, π.χ. του ΚΕΣΥ θα πρέπει να φροντίσει ώστε να συνταχθούν εθνικά πρωτόκολλα για την αντιμετώπιση οξέων ψυχιατρικών περιστατικών στους νέους, σε συνεργασία με φορείς όπως η Παιδοψυχιατρική Εταιρεία και συναφείς Παιδιατρικές Εταιρείες και Ενώσεις.

    -   Η Πολιτεία οφείλει να καταγράψει τις ανάγκες του δημοσίου συστήματος υγείας και ειδικότερα της παιδικής ψυχικής υγείας στο μεγαλύτερο νοσοκομείο της χώρα και να πράξει τα δέοντα, μ.α. απαραίτητες προσλήψεις και εκπαιδεύσεις προσωπικού,  στην υπηρεσία των νέων ασθενών και των οικογενειών τους.
